version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: eda_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./backend/media:/app/media
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:80
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 config.wsgi:application"

  frontend:
    build:
      context: ./frontend
    container_name: eda_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
